FROM python:3.6

# create project folder with the name code
RUN mkdir /code

# project scope
WORKDIR /code

ENV NODE_HUB_ADDRESS="hub"
ENV BROWSER=""

# install requirements
COPY ./requirements.txt .
RUN pip install --upgrade -r requirements.txt

# Set Docker entry
RUN pwd
COPY . /code
CMD python parallel_test_run.py
#CMD (export BROWSER=chrome && python -m unittest test.py) & (export BROWSER=chrome && python -m unittest test.py)
