FROM python:3.6

# create project folder with the name code
RUN mkdir /code

# project scope
WORKDIR /code

ENV NODE_HUB_ADDRESS="hub"

# install requirements
COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN ["chmod", "+x", "/opt/buildagent/temp/agentTmp/docker-shell-script-3187028531075530930.sh"]

# Set Docker entry
RUN pwd
COPY . /code
CMD python -m pytest parallel_test_run.py
#ENTRYPOINT python -m pytest parallel_test_run.py
