FROM python:3.6

# create project folder with the name code
RUN mkdir /code

# project scope
WORKDIR /code

ENV NODE_HUB_ADDRESS="hub"

# install requirements
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Set Docker entry
RUN pwd
COPY . /code
CMD python -m unittest parallel_test_run.py
