version: '3.8'
services:
  
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - selenium-net
    healthcheck:
      test: /opt/bin/check-grid.sh --host hub --port 4444
      interval: 15s
      #start_period: 20s
      timeout: 30s
      retries: 5
    
  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    ports:
      - 5900:5900
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - selenium-net
    
  firefox:
    image: selenium/node-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5556" /opt/bin/entry_point.sh'
    ports:
      - 5901:5900
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - selenium-net

networks:
  selenium-net:
    driver: overlay
