version: '3.8'

services:
  test:
    image: test:1.0.0
    environment:
      NODE_HUB_ADDRESS: "hub"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - grid_selenium-net

networks:
  grid_selenium-net:
    driver: overlay
    external: true
