version: '3.8'

services:
  test:
    image: test:1
    build: .
    environment:
      NODE_HUB_ADDRESS: "hub"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - tc_tc-net

networks:
  tc_tc-net:
    driver: overlay
    external: true
